### ISSUE TITLE
The SNP browser is not correct

### ISSUE THREAD

**Issue by squirrelB** [genenetwork/genenetwork2#365]
Hi, I think the variant browser needs looking at. The Mb location and the annotated genes do not match. If you search by gene name, the browser takes you to the correct mm10 location for that gene, but the annotated genes in the browser are different. If you search by mb location, the "gene" column consists of genes that aren't located there.

**Comment by zsloan** [comment]
I think you're referring to an issue stemming from data being encoded strangely/incorrectly in our database. In the database, there are many SNPs with the domain set as "intergenic" (because "intergenic" was set as the "default" domain value) and someone pointed out that it is strange that you can search for a gene and have a bunch of intergenic results for SNPs within its range. As a result we did a temporary partial "fix" where, if the user searches for a gene, all results within that range should at least show the associated gene instead of "intergenic." But this has the problem you noticed where, if you instead search for a range, it won't correctly identify many SNPs that are actually on a gene.

Thanks for making this comment, since I had completely forgotten that I needed to go back and address this. I think I know how to fix it, so I'll hopefully have the fix up by early next week.

**Comment by zsloan** [comment]
This issue should be fixed now. It should now check whether any given SNP is actually on a gene and indicate as much in the results.

Thanks again for bringing this to our attention and let me know if you encounter any other issues.

**Comment by squirrelB** [comment]
Hi Zach. (and this is Beni BTW). It's not fixed. Here's an example of the problem. Go to the SNP browser and search by chr:3, Mb 103 to 104. Click on any of the SNPs... for examples click on SNP with ID wt37-3-103158197 (supposed to be in exon of gene Trim33). In the UCSC Genome browser, mm10, that's in the intron of Dennd2c, a gene upstream of Trim33. So are these coordinates not mm10? Thanks for looking into this.

**Comment by zsloan** [comment]
Ohh, I thought you were referring to a separate issue (where searching for
a range instead of a gene causes different results in the Gene column).

I found the result of the issue, and it seems to be an issue in the actual
database. There are separate columns in the DB for the different domains
that list transcripts for the given SNP (like in this case there are
transcripts listed in a "3' UTR" column), and I'm pretty sure the gene
names listed there are from an older assembly. In the meanwhile I can do a
quick fix just to make sure the position corresponds to the correct gene,
and that should at least make that column appear correctly.

**Comment by zsloan** [comment]
Actually, I think this is a bigger problem. I can correct the gene name, but I think that the domain columns are also wrong and based on an outdated assembly.

It's a really good thing you mentioned this, because it makes updating (and likely changing the structure of) this table is a higher priority.

**Comment by zsloan** [comment]
Moved this to "Later" on the Trello board since it's not exactly a software bug.
